### ISSUE TITLE
The reconstruction of mae_pretrain_vit_base.pth is awful, is it right?

### ISSUE THREAD

**Issue by zheng547** [facebookresearch/mae#156]
I use the pre-trained model from https://dl.fbaipublicfiles.com/mae/pretrain/mae_pretrain_vit_base.pth.
![image](https://user-images.githubusercontent.com/54466644/222084672-3dddd7be-4548-4307-944e-167984adc445.png)

**Comment by babar414** [comment]
Hi, this could be due to your pretrained model does not contained the weights of the decoder part as you may be using the pretrained model which is supposed to be used for finetuning/probing but not visualizing. You may try the model that is mentioned in the demo notebook provided by the authors at below link:

https://github.com/facebookresearch/mae/blob/main/demo/mae_visualize.ipynb

**Comment by liuchenxin666** [comment]
But when i use the "mae_visualize_vit_large_ganloss.pth" or "mae_visualize_vit_large.pth" for visualizing, i get the same awful reconstruction. I don't know where the problem is. The code is in [https://github.com/liuchenxin666/mae_visualize/blob/main/mae_visualize.py](url).
