### ISSUE TITLE
Does someone reproduce the accuracy of imagenet1k?

### ISSUE THREAD

**Issue by KeyKy** [facebookresearch/mae#47]
Could someone share the log of reproducing the accuracy of imagenet1k?

**Comment by KeyKy** [comment]
the paper give the exp of imagenet1k however this repo seem to train in imagenet.

**Comment by endernewton** [comment]
For clarification, here ImageNet is ImageNet1K.

**Comment by KeyKy** [comment]
@endernewton Whether ImageNet1K is imagenet with 1000 classes or imagenet with 1000 training image?

**Comment by yuzhiguo07** [comment]
I have a very very basic question: which one is the ImageNet-1K on ImageNet's official website (https://image-net.org/download-images.php)? Since I only found the link of ImageNet21K and ILSVRC 2012-2017. I tried to download ILSVRC 2012, and the structure is a little bit difference with the Data preparation:
```
/path/to/imagenet/
  train/
    class1/
      img1.jpeg
    class2/
      img2.jpeg
  val/
    class1/
      img3.jpeg
    class2/
      img4.jpeg
```
 in https://github.com/facebookresearch/deit/blob/main/README_deit.md. The train folder is correct, but the val folder is different: There is no class level folder.
```
  ILSVRC2012_img_val/
      img1.jpeg  
      img2.jpeg
      img3.jpeg
```

Sorry I'm a rookie in CV.
