### ISSUE TITLE
fine-tuned checkpoint

### ISSUE THREAD

**Issue by mitchellnw** [facebookresearch/mae#6]
Hello, do you by any chance have a checkpoint for the model fine-tuned on ImageNet instead of pretrained?

**Comment by KaimingHe** [comment]
Please see https://github.com/facebookresearch/mae/blob/main/FINETUNE.md

**Comment by mitchellnw** [comment]
thank you

**Comment by hila-chefer** [comment]
Hi @KaimingHe, thanks for your great work and detailed implementation!
I see in your [README](https://github.com/facebookresearch/mae/blob/main/FINETUNE.md) that you used global pooling instead of the class token. Do you provide fine-tuned weights for using the class token instead of global pooling?
Additionally, have you tried visualizing your attention maps when using global pooling/ classification token?

Thanks in advance!
